name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Create .env file
        run: |
          echo "MONGO_URL=${{ secrets.MONGO_URL }}" > backend/.env
        env:
          MONGO_URL: ${{ secrets.MONGO_URL }}

      - name: Install Google Chrome
        run: |
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Debug directory structure
        run: ls -la && ls -la tests/selenium || echo "tests/selenium directory not found"

      - name: Install dependencies
        run: npm run setup

      - name: Build Frontend
        run: npm run build:frontend

      - name: Debug Frontend Build
        run: ls -la frontend/build || echo "Frontend build directory not found"

      - name: Start Backend
        run: cd backend && npm run ci:start &
        timeout-minutes: 2

      - name: Debug Backend Logs
        run: sleep 10 && curl -s http://localhost:4000/health || echo "Backend health check failed"
        timeout-minutes: 2

      - name: Start Frontend
        run: npm run serve:frontend &
        timeout-minutes: 2

      - name: Debug Frontend Logs
        run: sleep 10 && curl -s http://localhost:3000 || echo "Frontend status check failed"
        timeout-minutes: 2

      - name: Wait for Services
        run: npx wait-on http://localhost:4000/health http://localhost:3000 --timeout 60000
        timeout-minutes: 2

      - name: Run Selenium Tests
        run: npm run test:selenium